CREATE DATABASE THITH
USE THITH
SET DATEFORMAT DMY

--CAU 1--
CREATE TABLE DONVI(
	MADV CHAR(4) PRIMARY KEY,
	TENDV VARCHAR(5),
	MANV_TDV CHAR(4),
	NGNC SMALLDATETIME
)

CREATE TABLE NGACH(
	MANG CHAR(5) PRIMARY KEY,
	TENNG VARCHAR(10),
	HESO FLOAT,
	LUONGTN MONEY,
	LUONGCN MONEY
)

CREATE TABLE NHANVIEN(
	MANV CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(20),
	GIOITINH VARCHAR(3),
	NGLV SMALLDATETIME,
	MADV CHAR(4) FOREIGN KEY REFERENCES DONVI(MADV),
	TRINHDOHV VARCHAR(5),
	MANG CHAR(5) FOREIGN KEY REFERENCES NGACH(MANG),
	LUONG MONEY
)

--CAU 2: tăng 10% lương đối với những nhân viên vào làm trước ngay '1/1/1990'--
UPDATE NHANVIEN 
SET LUONG = 1.1 * LUONG
WHERE YEAR(NGLV) <= 1989 

--CAU 4--
--A--
SELECT NV.MANV, NV.HOTEN, NV.LUONG
FROM NHANVIEN NV JOIN DONVI DV ON NV.MANV = DV.MANV_TDV 
WHERE NV.GIOITINH = 'nữ' AND NV.TRINHDOHV = 'Sau đại học' 
ORDER BY NV.LUONG	

--B: Tìm ngạch chưa có nhân viên nào vào làm sau ngày '1/1/2018' mà trình độ học vấn là 'Sau đại học'--
SELECT NG.MANG, NG.TENNG
FROM NGACH NG 
EXCEPT 
SELECT NG.MANG, NG.TENNG
FROM NGACH NG JOIN NHANVIEN NV ON NG.MANG = NV.MANG 
WHERE NGLV >= '1/1/2018'AND NV.TRINHDOHV = 'Sau đại học' 

--C: Tìm trưởng đơn vị cuả đơn vị có ít nhân viên nhất--
SELECT TOP 1 WITH TIES DV.MANV_TDV, HOTEN
FROM DONVI DV JOIN NHANVIEN NV ON DV.MANV_TDV = NV.MANV
GROUP BY DV.MANV_TDV, HOTEN
ORDER BY COUNT(NV.MANV) 

--D: Tìm ngạch mà tất cả các đơn vị đều có ít nhất 1 nv giới tính nữ thuộc ngach đó--
SELECT NG.MANG, NG.TENNG
FROM NGACH NG
WHERE NOT EXISTS (
    SELECT *
    FROM DONVI DV
    WHERE NOT EXISTS (
        SELECT *
        FROM NHANVIEN NV
        WHERE NV.GIOITINH = 'Nữ' AND NV.MANG = NG.MANG AND NV.MADV = DV.MADV
    )
)

--E: Mỗi đơn vị, tìm nhân viên có lương hang tháng cao nhất. Hiện thị: MADV, TENDV, MANV, HOTEN--
SELECT DV.MADV, DV.TENDV, NV.MANV, NV.HOTEN
FROM DONVI DV JOIN NHANVIEN NV ON DV.MADV = NV.MADV
WHERE NV.LUONG = (
	SELECT MAX(LUONG)
    FROM NHANVIEN
	WHERE MADV = DV.MADV
)

--CAU 3--
--A: Giá trị lương thấp nhất nhỏ hơn lương cao nhất tối thiểu 100000 và tối đa 2000000--
ALTER TABLE NGACH
ADD CONSTRAINT CK_A
CHECK (1000000 <= LUONGCN - LUONGTN AND LUONGCN - LUONGTN <= 2000000)

--B--
GO
CREATE TRIGGER R ON NHANVIEN FOR INSERT
AS
	IF EXISTS(SELECT * FROM DONVI DV, INSERTED I
						WHERE DV.MANV_TDV = I.MANV AND NGLV < NGNC)
	BEGIN
		RAISERROR('Truong don vi phai co ngay vao lam lon hon hoac bang ngay nhan chuc', 16, 1)
		ROLLBACK TRAN 
	END
