--DE 1--
--1, 2--
CREATE DATABASE QLGTA
USE QLGTA
SET DATEFORMAT DMY

CREATE TABLE KHACHHANG(
	MAKH VARCHAR(10) PRIMARY KEY,
	HO VARCHAR(10),
	TEN VARCHAR(20),
	NGAYSINH SMALLDATETIME,
	DIACHI VARCHAR(50),
	SDT VARCHAR(20)
)

CREATE TABLE MONAN(
	MAMA VARCHAR(10) PRIMARY KEY,
	TENMA VARCHAR(20),
	LOAIMA VARCHAR(20)
)

CREATE TABLE HOADON(
	MAHD VARCHAR(10) PRIMARY KEY,
	MAKH VARCHAR(10) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	NGAYHD SMALLDATETIME
)

CREATE TABLE CTHD(
	MAHD VARCHAR(10) FOREIGN KEY REFERENCES HOADON(MAHD),
	MAMA VARCHAR(10) FOREIGN KEY REFERENCES MONAN(MAMA),
	SL INT,
	DONGIA MONEY
)

--4--
SELECT MAKH, HO, TEN, DIACHI
FROM KHACHHANG 
WHERE YEAR(NGAYSINH) = 2002
ORDER BY DIACHI DESC, HO ASC

--5--
SELECT LOAIMA, COUNT(MAMA) AS SL_MONAN
FROM MONAN
GROUP BY LOAIMA 

--6--
SELECT TOP 1 WITH TIES KH.MAKH, HO, TEN 
FROM KHACHHANG KH JOIN HOADON HD ON KH.MAKH = HD.MAKH 
	JOIN CTHD CT ON CT.MAHD = HD.MAHD
ORDER BY DONGIA DESC 

--7--
SELECT SUM(SL) AS SL_TREN
FROM CTHD CT 
WHERE DONGIA > 50000 
UNION
SELECT SUM(SL) AS SL_DUOI
FROM CTHD CT 
WHERE DONGIA < 50000

--3--
GO
CREATE TRIGGER R1 ON MONAN FOR INSERT, UPDATE 
AS
	IF UPDATE(LOAIMA)
		IF EXISTS(SELECT * FROM MONAN M, INSERTED I 
								WHERE M.MAMA = I.MAMA AND I.LOAIMA NOT IN('Canh', 'Man', 'Xao', 'Trang mieng'))
		BEGIN
			RAISERROR('Them va cap nhat len quan he MONAN phai dam bao loai thuc an phai la: Canh, man, xao, trang mieng', 16, 1)
			ROLLBACK TRAN
		END 

--DE 2--
--3--
GO
CREATE TRIGGER R2 ON HOADON FOR INSERT, UPDATE 
AS 
	IF UPDATE(NGAYHD)
		IF EXISTS(SELECT * FROM HOADON HD, INSERTED I
							WHERE HD.MAHD = I.MAHD AND (YEAR(I.NGAYHD) = 2021 AND MONTH(I.NGAYHD) <= 10) OR (YEAR(I.NGAYHD) < 2021))
		BEGIN 
			RAISERROR('Hoa don phai duoc lap sau thang 10 nam 2021', 16, 1)
			ROLLBACK TRAN
		END 

--4--
SELECT MAKH, HO, TEN, DIACHI
FROM KHACHHANG
WHERE YEAR(NGAYSINH) != 2002 
ORDER BY HO DESC, TEN ASC

--5--
SELECT DAY(NGAYHD), COUNT(MAHD) AS SL_HOADON
FROM HOADON
GROUP BY DAY(NGAYHD)

--6--
SELECT TOP 1 WITH TIES M.MAMA, TENMA
FROM MONAN M JOIN CTHD CT ON M.MAMA = CT.MAMA 
	JOIN HOADON HD ON HD.MAHD = CT.MAHD
		JOIN KHACHHANG KH ON KH.MAKH = HD.MAKH
ORDER BY YEAR(NGAYSINH) --khong can group by--
