--cau 1--
CREATE DATABASE BAITHI
USE BAITHI
SET DATEFORMAT DMY

CREATE TABLE KHACHHANG(
	MAKH CHAR(4) PRIMARY KEY,
	TENKH VARCHAR(50),
	DIACHI VARCHAR(50),
	LOAIKH VARCHAR(50)
)

CREATE TABLE LOAICAY(
	MALC CHAR(4) PRIMARY KEY,
	TENLC VARCHAR(50),
	XUATXU VARCHAR(50),
	GIA MONEY
)

CREATE TABLE HOADON(
	SOHD CHAR(5) PRIMARY KEY,
	NGHD SMALLDATETIME,
	MAKH CHAR(4) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	KHUYENMAI INT
)

CREATE TABLE CTHD(
	SOHD CHAR(5) FOREIGN KEY REFERENCES HOADON(SOHD),
	MALC CHAR(4) FOREIGN KEY REFERENCES LOAICAY(MALC),
	SOLUONG INT,
	PRIMARY KEY(SOHD, MALC)
)

--cau 2--
INSERT INTO KHACHHANG VALUES('KH01', 'Liz Kim Cuong', 'Ha Noi', 'Vang lai')
INSERT INTO KHACHHANG VALUES('KH02', 'Ivone Dieu Linh', 'Da Nang', 'Thuong xuyen')
INSERT INTO KHACHHANG VALUES('KH03', 'Emma Nhat Khanh', 'TP.HCM', 'Vang lai')

INSERT INTO LOAICAY VALUES('LC01', 'Xuong rong tai tho', 'Mexico', 180000)
INSERT INTO LOAICAY VALUES('LC02', 'Sen thach ngoc', 'Anh', 300000)
INSERT INTO LOAICAY VALUES('LC03', 'Ba mau rau', 'Nam Phi', 270000)

INSERT INTO HOADON VALUES('00001', '22/11/2017', 'KH01', 5)
INSERT INTO HOADON VALUES('00002', '04/12/2017', 'KH03', 5)
INSERT INTO HOADON VALUES('00003', '10/12/2017', 'KH02', 10)

INSERT INTO CTHD VALUES('00001', 'LC01', 1)
INSERT INTO CTHD VALUES('00001', 'LC02', 2)
INSERT INTO CTHD VALUES('00003', 'LC03', 5)


--cau 3--
ALTER TABLE LOAICAY
ADD CONSTRAINT CK_LC
CHECK (XUATXU = 'Anh' AND GIA > 250000 OR XUATXU != 'Anh')

--cau 5--
SELECT *
FROM HOADON
WHERE YEAR(NGHD) = 2017 AND MONTH(NGHD) BETWEEN 10 AND 12
ORDER BY KHUYENMAI

--cau 6--
SELECT TOP 1 WITH TIES LC.MALC, TENLC, XUATXU, GIA
FROM LOAICAY LC JOIN CTHD CT ON LC.MALC = CT.MALC 
	JOIN HOADON HD ON HD.SOHD = CT.SOHD
WHERE MONTH(NGHD) = 12
GROUP BY LC.MALC, TENLC, XUATXU, GIA
ORDER BY SUM(SOLUONG) 

--cau 7--
SELECT LC.MALC, TENLC, XUATXU, GIA
FROM LOAICAY LC JOIN CTHD CT ON LC.MALC = CT.MALC
	JOIN HOADON HD ON CT.SOHD = HD.SOHD
		JOIN KHACHHANG KH ON KH.MAKH = HD.MAKH
WHERE LOAIKH = 'Thuong xuyen' AND LC.MALC IN(
	SELECT CT.MALC
	FROM CTHD CT JOIN HOADON HD ON HD.SOHD = CT.SOHD 
		JOIN KHACHHANG KH ON KH.MAKH = HD.MAKH
	WHERE LOAIKH = 'Vang lai'
)

--cau 8--
SELECT *
FROM KHACHHANG KH
WHERE NOT EXISTS(
	SELECT *
	FROM LOAICAY LC
	WHERE NOT EXISTS(
		SELECT *
		FROM HOADON HD JOIN CTHD CT ON HD.SOHD = CT.SOHD
		WHERE HD.MAKH = KH.MAKH AND CT.MALC = LC.MALC
	)
)

--cau 4--
/*bang rang buoc toan ven:
         T      X      S
CTHD  |  +  |   -   |  +(SOHD, SOLUONG)
HOADON|  -  |  -   |  +(KHUYENMAI)
*/
GO
CREATE TRIGGER R1 ON HOADON FOR UPDATE 
AS
	IF UPDATE(KHUYENMAI)
		IF EXISTS(SELECT I.SOHD, NGHD, MAKH, KHUYENMAI 
							FROM CTHD CT, INSERTED I
							WHERE CT.SOHD = I.SOHD AND KHUYENMAI != 10
							GROUP BY I.SOHD, NGHD, MAKH, KHUYENMAI 
							HAVING SUM(SOLUONG) >= 5)
		BEGIN
			RAISERROR('Hoa don mua voi so luong tong cong lon hon hoac bang 5 phai duoc giam gia 10 phan tram', 16, 1)
			ROLLBACK TRAN
		END 

GO
CREATE TRIGGER R2 ON CTHD FOR UPDATE, INSERT 
AS
	IF EXISTS(SELECT I.SOHD, MALC, SOLUONG
						FROM HOADON HD, INSERTED I 
						WHERE HD.SOHD = I.SOHD AND KHUYENMAI != 10
						GROUP BY I.SOHD, MALC, SOLUONG
						HAVING SUM(SOLUONG) >= 5)
	BEGIN
		RAISERROR('Hoa don mua voi so luong tong cong lon hon hoac bang 5 phai duoc giam gia 10 phan tram', 16, 1)
		ROLLBACK TRAN
	END 

