--cau 1--
CREATE DATABASE QLNK
USE QLNK
SET DATEFORMAT DMY

CREATE TABLE NHACUNGCAP(
	MANCC CHAR(5) PRIMARY KEY,
	TENNCC VARCHAR(50),
	QUOCGIA VARCHAR(50),
	LOAINCC VARCHAR(50)
)

CREATE TABLE DUOCPHAM(
	MADP CHAR(4) PRIMARY KEY,
	TENDP VARCHAR(50),
	LOAIDP VARCHAR(50),
	GIA MONEY
)

CREATE TABLE PHIEUNHAP(
	SOPN CHAR(5) PRIMARY KEY,
	NGNHAP SMALLDATETIME,
	MANCC CHAR(5) FOREIGN KEY REFERENCES NHACUNGCAP(MANCC),
	LOAINHAP VARCHAR(50)
)

CREATE TABLE CTPN(
	SOPN CHAR(5) FOREIGN KEY REFERENCES PHIEUNHAP(SOPN),
	MADP CHAR(4) FOREIGN KEY REFERENCES DUOCPHAM(MADP),
	SOLUONG INT
	PRIMARY KEY(SOPN, MADP)
)

--cau 2--
INSERT INTO NHACUNGCAP VALUES('NCC01', 'Phuc Hung', 'Viet Nam', 'Thuong xuyen')
INSERT INTO NHACUNGCAP VALUES('NCC02', 'J. B. Pharmaceuticals', 'India', 'Vang lai')
INSERT INTO NHACUNGCAP VALUES('NCC03', 'Sapharco', 'Singapore', 'Vang lai')

INSERT INTO DUOCPHAM VALUES('DP01', 'Thuoc ho PH', 'Siro', '120000')
INSERT INTO DUOCPHAM VALUES('DP02', 'Zecuf Herbal CouchRemedy', 'Vien nen', '200000')
INSERT INTO DUOCPHAM VALUES('DP03', 'Cotrim', 'Vien sui', '80000')

INSERT INTO PHIEUNHAP VALUES('00001', '22/11/2017', 'NCC01', 'Noi dia')
INSERT INTO PHIEUNHAP VALUES('00002', '04/12/2017', 'NCC03', 'Nhap khau')
INSERT INTO PHIEUNHAP VALUES('00003', '10/12/2017', 'NCC02', 'Nhap khau')

INSERT INTO CTPN VALUES('00001', 'DP01', 100)
INSERT INTO CTPN VALUES('00001', 'DP02', 200)
INSERT INTO CTPN VALUES('00003', 'DP03', 543)

--cau 5--
SELECT *
FROM PHIEUNHAP
WHERE YEAR(NGNHAP) = 2017 AND MONTH(NGNHAP) = 12
ORDER BY DAY(NGNHAP)

--cau 6--
SELECT TOP 1 WITH TIES DP.MADP, TENDP, LOAIDP, GIA
FROM DUOCPHAM DP JOIN CTPN CT ON DP.MADP = CT.MADP
	JOIN PHIEUNHAP PN ON PN.SOPN = CT.SOPN
WHERE YEAR(NGNHAP) = 2017
GROUP BY DP.MADP, TENDP, LOAIDP, GIA
ORDER BY SUM(SOLUONG) DESC

--cau 7-- 
SELECT *
FROM DUOCPHAM DP JOIN CTPN CT ON CT.MADP = DP.MADP 
	JOIN PHIEUNHAP PN ON PN.SOPN = CT.SOPN
		JOIN NHACUNGCAP NCC ON NCC.MANCC = PN.MANCC
WHERE LOAINCC = 'Thuong xuyen' AND DP.MADP NOT IN(
	SELECT MADP
	FROM CTPN CT JOIN PHIEUNHAP PN ON CT.SOPN = PN.SOPN
		JOIN NHACUNGCAP NCC ON NCC.MANCC = PN.MANCC
	WHERE LOAINCC = 'Vang lai'
)

--cau 8--
SELECT *
FROM NHACUNGCAP NCC
WHERE NOT EXISTS(
	SELECT *
	FROM DUOCPHAM DP JOIN CTPN CT ON DP.MADP = CT.MADP
		JOIN PHIEUNHAP PN ON PN.SOPN = CT.SOPN
	WHERE GIA > 100000 AND YEAR(NGNHAP) = 2017 AND NOT EXISTS(
		SELECT *
		FROM PHIEUNHAP PN1, CTPN CT1
		WHERE PN1.MANCC = NCC.MANCC AND PN1.SOPN = CT1.SOPN AND PN1.MANCC = NCC.MANCC
	)
)

--cau 3--
ALTER TABLE DUOCPHAM
ADD CONSTRAINT check_c3
CHECK (LOAIDP = 'Siro' AND GIA > 100000 OR LOAIDP != 'Siro')

--cau 4: PHIEUNHAP vs NHACUNGCAP--
/*Bang tam anh huong:
            t    x     s
PHIEUNHAP | + |  -  |  + (MANCC, LOAINHAP)
NHACUNGCAP| - |  -  |  + (QUOCGIA)

*/
GO
CREATE TRIGGER R1 ON NHACUNGCAP FOR UPDATE 
AS
	IF UPDATE(QUOCGIA)
		IF EXISTS(SELECT * FROM PHIEUNHAP PN, INSERTED I 
							WHERE PN.MANCC = I.MANCC 
								AND I.QUOCGIA = 'Việt Nam' AND PN.LOAINHAP = 'Nhập khẩu')
		BEGIN
			RAISERROR('Phiếu nhập của những nhà cung cấp ở những quốc gia khác Việt Nam đều có loại nhập là Nhập khẩu', 16, 1)
			ROLLBACK TRAN
	END

GO
CREATE TRIGGER R2 ON PHIEUNHAP FOR UPDATE, INSERT 
AS
	IF EXISTS(SELECT * FROM NHACUNGCAP NCC, INSERTED I
						WHERE NCC.MANCC = I.MANCC
							AND NCC.QUOCGIA = 'Việt Nam' AND I.LOAINHAP = 'Nhập khẩu')
	BEGIN
		RAISERROR('Phiếu nhập của những nhà cung cấp ở những quốc gia khác Việt Nam đều có loại nhập là Nhập khẩu', 16, 1)
		ROLLBACK TRAN
	END





