--cau 1--
USE MASTER
CREATE DATABASE QLNK
USE QLNK

CREATE TABLE NHACUNGCAP(
	MANCC CHAR(100) PRIMARY KEY,
	TENNCC CHAR(100),
	QUOCGIA CHAR(100),
	LOAINCC CHAR(100)
)

CREATE TABLE DUOCPHAM(
	MADP CHAR(100) PRIMARY KEY,
	TENDP CHAR(100),
	LOAIDP CHAR(100),
	GIA FLOAT
)

CREATE TABLE PHIEUNHAP(
	SOPN CHAR(100) PRIMARY KEY,
	NGNHAP DATETIME,
	MANCC CHAR(100) FOREIGN KEY REFERENCES NHACUNGCAP(MANCC),
	LOAINHAP CHAR(100)
)

CREATE TABLE CTPN(
	SOPN CHAR(100) FOREIGN KEY REFERENCES PHIEUNHAP(SOPN),
	MADP CHAR(100) FOREIGN KEY REFERENCES DUOCPHAM(MADP),
	SOLUONG INT
)

--cau 2--
INSERT INTO NHACUNGCAP VALUES('NCC01', 'Phuc Hung', 'Viet Nam', 'Thuong xuyen')
INSERT INTO NHACUNGCAP VALUES('NCC02', 'J. B. Pharmaceuticals', 'India', 'Vang lai')
INSERT INTO NHACUNGCAP VALUES('NCC03', 'Sapharco', 'Singapore', 'Vang lai')

INSERT INTO DUOCPHAM VALUES('DP01', 'Thuoc ho PH', 'Siro', '120000')
INSERT INTO DUOCPHAM VALUES('DP02', 'Zecuf Herbal CouchRemedy', 'Vien nen', '200000')
INSERT INTO DUOCPHAM VALUES('DP03', 'Cotrim', 'Vien sui', '80000')

INSERT INTO PHIEUNHAP VALUES('00001', '22/11/2017', 'NCC01', 'Noi dia')
INSERT INTO PHIEUNHAP VALUES('00002', '04/12/2017', 'NCC03', 'Nhap khau')
INSERT INTO PHIEUNHAP VALUES('00003', '10/12/2017', 'NCC02', 'Nhap khau')

INSERT INTO CTPN VALUES('00001', 'DP01', 100)
INSERT INTO CTPN VALUES('00001', 'DP02', 200)
INSERT INTO CTPN VALUES('00003', 'DP03', 543)

--cau 5--
SELECT *
FROM PHIEUNHAP
WHERE YEAR(NGNHAP) = 2017 AND MONTH(NGNHAP) = 12
ORDER BY DAY(NGNHAP)

--cau 6--
SELECT TOP 1 WITH TIES *
FROM DUOCPHAM DP JOIN CTPN CT ON DP.MADP = CT.MADP
	JOIN PHEUNHAP PN ON PN.SOPN = CT.SOPN
WHERE YEAR(NGNHAP) = 2017
GROUP BY MADP
ORDER BY SUM(SOLUONG) DESC

--cau 7-- 
SELECT *
FROM DUOCPHAM DP JOIN CTPN CT ON CT.MADP = DP.MADP 
	JOIN PHIEUNHAP PN ON PN.SOPN = CT.SOPN
		JOIN NHACUNGCAP NCC ON NCC.MANCC = PN.MANCC
WHERE LOAINCC = 'Thuong xuyen' AND MADP NOT IN(
	SELECT MADP
	FROM CTPN CT JOIN PHIEUNHAP PN ON CT.SOPN = PN.SOPN
		JOIN NHACUNGCAP NCC ON NCC.MANCC = PN.MANCC
	WHERE LOAINCC = 'Vang lai'
)

--cau 8--
SELECT *
FROM NHACUNGCAP NCC
WHERE NOT EXISTS(
	SELECT *
	FROM DUOCPHAM DP JOIN CTPN CT ON DP.MADP = CT.MADP
		JOIN PHIEUNHAP PN ON PN.SOPN = CT.SOPN
	WHERE GIA > 100000 AND YEAR(NGNHAP) = 2017 AND NOT EXISTS(
		SELECT *
		FROM PHIEUNHAP PN1
		WHERE PN1.MANCC = NCC.MANCC AND PN1.MADP = DP.MADP
	)
)

--cau 3--
ALTER TABLE DUOCPHAM
ADD CONSTRAINT check_c3
CHECK (LOAIDP = 'Siro' AND GIA > 100000 OR LOAIDP != 'Siro')

--cau 4: PHIEUNHAP vs NHACUNGCAP--
/*Bang tam anh huong:
            t    x     s
PHIEUNHAP | + |  -  |  + (MANCC, LOAINHAP)
NHACUNGCAP| - |  -  |  + (QUOCGIA)

*/
CREATE TRIGGER R1 ON NHACUNGCAP FOR UPDATE 
AS
	IF UPDATE(QUOCGIA)
		IF EXISTS(SELECT * FROM PHIEUNHAP PN, INSERTED I 
							WHERE PN.MANCC = I.MANCC 
								AND I.QUOCGIA = 'Việt Nam' AND PN.LOAINHAP = 'Nhập khẩu')
		BEGIN
			RAISERROR('Phiếu nhập của những nhà cung cấp ở những quốc gia khác Việt Nam đều có loại nhập là Nhập khẩu', 16, 1)
			ROLLBACK TRAN
	END

CREATE TRIGGER R2 ON PHIEUNHAP FOR UPDATE, INSERT 
AS
	IF EXISTS(SELECT * FROM NHACUNGCAP NCC, INSERTED I
						WHERE NCC.MANCC = I.MANCC
							AND NCC.QUOCGIA = 'Việt Nam' AND PN.LOAINHAP = 'Nhập khẩu')
	BEGIN
		RAISERROR('Phiếu nhập của những nhà cung cấp ở những quốc gia khác Việt Nam đều có loại nhập là Nhập khẩu', 16, 1)
		ROLLBACK TRAN
	END



